### PR TITLE
update composer.json dependencies

### PR DESCRIPTION
**Pull request by sonrac**
1. Php 7.0&5.6 working fine with service provider.
2. Remove composer.lock. Composer.lock commited only for projects not library
https://travis-ci.org/sonrac/silex-doctrine-migrations-provider/builds/361233078
for more details.

### CODE REVIEW

**Comment by breenie** [comment]
Hi, thanks for the pr. Can you cleanup the indentation in the composer.json so the diff is clear? I’ve never seen a recommendation to not include a composer.lock, do you have any links?

**Comment by hkdobrev** [comment]
Hi @sonrac! Thank you for your contribution!

While I personally like Travis CI, the library is tested on Circle CI.

Also, `composer.lock` is completely fine to be committed to a library to share locked dependencies across collaborators.
See [the official docs](https://getcomposer.org/doc/02-libraries.md#lock-file) and [this related issue](https://github.com/composer/composer/issues/2461).

What could be added is to test on both locked, highest and lowest version constraints.

There are a bit unrelated changes here like re-formatting `composer.json` making it harder to see what actually changed and what didn't.

**Comment by sonrac** [comment]
Local php version
`$ php --version 
PHP 7.1.15-1 (cli) (built: Mar  6 2018 10:50:10) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.1.15-1, Copyright (c) 1999-2018, by Zend Technologies
    with Xdebug v2.6.0, Copyright (c) 2002-2018, by Derick Rethans
`

I'm adding composer.lock and test for php 5.6 was failed. This is because there are already dependencies for the project with the version of php 7.1, but they are not suitable for 5.6. 
https://travis-ci.org/sonrac/silex-doctrine-migrations-provider/jobs/361516435
for details.

Also, removing composer.lock and Travis CI task with php version 5.6 is done
https://travis-ci.org/sonrac/silex-doctrine-migrations-provider/jobs/361518443
for details

@hkdobrev I'm including travis for testing php another version. How to achieve this in the circleci I did not have time to understand. Remove travis-ci.yml ?

**Comment by breenie** [comment]
Hi @sonrac are you just trying to get the provider to work in php versions other than `^7.1` listed in the `composer.json`?

**Comment by sonrac** [comment]
@breenie Yes

**Comment by hkdobrev** [comment]
@breenie It looks good! I don't get just the `--prefer-source` flag. You could create a PR.

**Comment by breenie** [comment]
Closed in favour of #20

**Comment by breenie** [comment]
Thanks @sonrac you can composer update now to get this most PHP flavours.

**Pull request closed without merging**
