### PR TITLE
We have a stable release, youhou

### PR DESCRIPTION
**Pull request by mikeSimonson**

### CODE REVIEW

**Comment by breenie** [comment]
Hi, thanks for the PR. Sadly these changes cause the CI to fail. See https://circleci.com/gh/kurlltd/silex-doctrine-migrations-provider/16. It looks like doctrine/migrations require php 5.4.x but the composer.json in this projects states 5.3.x.

**Comment by mikeSimonson** [comment]
Well 5.3 and 5.4 are unsupported now.

**Comment by mikeSimonson** [comment]
You could tag a new version that support 5.5 onward and use a stable version of doctrine migrations.

**Comment by breenie** [comment]
I've had a look and ^5.5|^7.0 (lazily copy and pasted from doctrine migrations) works.

**Comment by mikeSimonson** [comment]
@breenie done but it seems like you have to update the circle ci configuration to test on 5.5, 5.6 and 7

**Comment by breenie** [comment]
Sure, good point. I'll update it tomorrow and do a release. Thanks.

**Comment by breenie** [comment]
Contrary to what the git hub report states this now passes CI. It was a royal pain due to some changes in doctrine migrations and some idiocy from me. I've released v0.2.0 so 0.1.x users don't have a nightmare on older php versions. Thanks for the PR.

**Pull request merged**
