### PR TITLE
Increase lazy loading to better support Pimple

### LINKED ISSUE #9: Support Pimple 3.x without Silex
@breenie What do you think of supporting Pimple-only installation when Silex is not present? I think this is the recommended way as it's more portable and could be used in projects using Doctrine and Pimple without using Silex. That's why the service provider was moved from Silex to Pimple and also why Silex now publish their providers as a separate Composer package.

This means not using the `BootableProviderInterface`. We could move everything to `register()` and make things more lazy. Getting the configuration object would be lazy through Pimple. The only obstacle is adding the commands - if we add them in the register method then the configuration would be retrieved from the container before any option overriding from the user has been applied. So we could still add the commands in the `boot` method, but if you are not using Silex you'd just need to add the commands yourself or even better - call the boot method on the provider yourself and it'd add the commands for you.

How do you feel about that? Do you want me to make a PR with the described suggestions so we could discuss a concrete implementation?

### PR DESCRIPTION
**Pull request by hkdobrev**
Closes #9.

### CODE REVIEW

**Comment by breenie** [comment]
Surely there is still reliance on Silex as the `boot` method requires a Silex instance? 

Anyway, in theory it all looks OK. The `DialogHelper` is deprecated though, this should be replaced with the `QuestionHelper` but I'm not sure how much upheaval this will cause under the hood or if they are even required any more.

**Comment by breenie** [comment]
Actually, having a quick look:

```
'dialog'     => new DialogHelper(),
```

Should be replaced with:

```
'question' => new QuestionHelper(),
```

**Comment by hkdobrev** [comment]
> Surely there is still reliance on Silex as the boot method requires a Silex instance?

Well, if you use Silex, `boot` would be executed automatically. If you don't use Silex, you can either run it yourself or just add the helper set and the commands yourself as this is now made very easy for you.

**Comment by hkdobrev** [comment]
If you're OK with this approach I'd like to update the documentation in the readme about this as well. Things got much more configurable. What do you think? Any help appreciated :)

**Comment by hkdobrev** [comment]
@breenie The `QuestionHelper` is added since `symfony/console` 2.5. Should I up the console requirements?

**Comment by breenie** [comment]
Good point, Migrations get around this by checking if the `'dialog'` key exists in the `HelperSet`. Symfony 2.3 is supported until 05/2017 so either up the requirement or check for existence of the class I guess.

**Comment by breenie** [comment]
But to boot it you'd need to pass a Silex instance (which you are trying to avoid using) and manual calling will not be possible because `$this->console` is protected. Adding the console object to the container might solve the issue ala `$app['console'] = $console;`. Then you can add the helperset and commands outside of the provider.

**Comment by hkdobrev** [comment]
> But to boot it you'd need to pass a Silex instance

Good point, haven't thought of that.

> and manual calling will not be possible because $this->console is protected

I don't think that would be a problem. Here's how I imagine this would be used:

`console` file which is the CLI entry point to the app:
``` php
<?php

// Configure autoloading, set up Pimple container with services
// Populates an `$app` variable which is the Pimple container instance
require 'app.php';

$consoleApplication = new \Symfony\Component\Console\Application();

$app->register(new \Kurl\Silex\Provider($consoleApplication));

$consoleApplication->setHelperSet($app['migrations.em_helper_set']);
$consoleApplication->addCommands($app['migrations.commands']);
```

What do you think?

**Comment by breenie** [comment]
Of course, you have access to the console object already. Yes, if you can also add that to the docs as how to do it if you aren't using Silex.

What did you think of with regards to the QuestionHelper vs the DialogHelper?

**Comment by hkdobrev** [comment]
I think it would be best to check for existence of the `QuestionHelper` class like you've suggested. If there's something bigger for which we need a newer Symfony Console version we can increase the minimum version constraint. But for this it should be fine and I've found that checking if a class exists is a popular practice in the Symfony world.

I'd rebase, do the check for the question helper and update the docs later today :)

**Comment by hkdobrev** [comment]
@breenie I've updated everything we've discussed. However while I was updating the documentation I was thinking we should make the console application instance passed to the constructor optional. It's not really needed for Pimple. And even if you use Silex you could choose to configure it yourself. We could just check if it was passed and only then do something in `boot()`.

For example my personal use case is the following:

I have three entry points to the application:
- Silex web request
- Web request through a legacy framework, but using Pimple as a service container
- CLI command which loads both Silex and the legacy framework

In all cases I configure the Pimple container the same way.

While in the case of the `DoctrineMigrationsProvider` this is not really valid as I would only register it when the app is accessed through CLI, what I want to say is that I'd always register it in the same way by manually adding the commands.

---

We could check both the private variable set through the constructor and `$app['console']`. This way Cilex CLI apps would have better support as well.

**Comment by breenie** [comment]
All looks good to me. I've implemented your suggestion. The getter is a bit verbose but I left it like that for readability.

```patch
diff --git a/src/DoctrineMigrationsProvider.php b/src/DoctrineMigrationsProvider.php
index c54af7f..e4e1aaf 100644
--- a/src/DoctrineMigrationsProvider.php
+++ b/src/DoctrineMigrationsProvider.php
@@ -30,7 +30,6 @@ class DoctrineMigrationsProvider implements
     ServiceProviderInterface,
     BootableProviderInterface
 {
-
     /**
      * The console application.
      *
@@ -43,7 +42,7 @@ class DoctrineMigrationsProvider implements
      *
      * @param Console $console
      */
-    public function __construct(Console $console)
+    public function __construct(Console $console = null)
     {
         $this->console = $console;
     }
@@ -116,6 +115,7 @@ class DoctrineMigrationsProvider implements
             if (true === $this->console->getHelperSet()->has('em')) {
                 $commands[] = MigrationsCommand\DiffCommand::class;
             }
+
             // @codeCoverageIgnoreEnd
 
             return $commands;
@@ -145,7 +145,33 @@ class DoctrineMigrationsProvider implements
      */
     public function boot(Application $app)
     {
-        $this->console->setHelperSet($app['migrations.em_helper_set']);
-        $this->console->addCommands($app['migrations.commands']);
+        $console = $this->getConsole($app);
+
+        $console->setHelperSet($app['migrations.em_helper_set']);
+        $console->addCommands($app['migrations.commands']);
+    }
+
+    /**
+     * Gets the console application.
+     *
+     * @param Container $app
+     *
+     * @return mixed|null|Console
+     */
+    public function getConsole(Container $app = null)
+    {
+        $console = null;
+
+        if (null !== $this->console) {
+            $console = $this->console;
+        } else {
+            if (null !== $app && false !== $app->offsetExists('console')) {
+                $console = $app['console'];
+            } else {
+                $console = new Console();
+            }
+        }
+
+        return $console;
     }
 }
```

(Fingers crossed the patch works in markdown :/)

**Comment by hkdobrev** [comment]
@breenie Thanks! The patch worked :) I was imagining something a bit simpler with getting though. For me the getter is OK to return `null`, no need to always return a `Console` instance as it could be misleading and the check is really simple on only two places. I've applied your commit and added my suggestions in the next one. What do you think?

Also I'm not sure there's need for the getter to be public. 💭

**Comment by hkdobrev** [comment]
Also what do you think about the updated readme any comments?

I'd also like to add more extensive tests covering the case of using Pimple alone. I'll try to add that tomorrow.

**Comment by hkdobrev** [comment]
@breenie I've updated the readme and tests. I think my tests are a bit verbose and could be dried up, but they cover all the important cases - pimple/Silex, console/no console/console from container etc. I think this is good to merge. What do you think?

**Comment by breenie** [comment]
Hi, sorry for the delay. I'm on holiday at the moment so won't be able to review/merge these until next week. 

Cheers
Chris

**Comment by breenie** [comment]
It's all looking good, there are a few missing items to provide 100% coverage but I'm OK with it. I think the tests would not be too worthwhile. 

I think there is one problem though, the test for the `QuestionHelper` requests `QuestionHelper::class` which will not exist and produce an error if the class does not exist. In this case I think we have to provide a hardcoded string. I've done some rudimentary tests which seem to confirm my hypothesis but feel free to correct me.

**Pull request merged**
